<a href="https://colab.research.google.com/github/signalmania2/he0119_21/blob/main/d_04_FileFolder_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파일 다루기
- 파일 열기 open(), with로 열기
- csv, xlsx 파일 다루기
- zip 파일 다루기
- 폴더 내 파일 목록 다루기 (glob, listdir)
- 폴더/파일 생성과 삭제

## import

In [1]:
import pandas as pd
import numpy as np
from numpy.random import rand
import csv
import os
from glob import glob

##  숫자 데이터  파일 생성
- 센서 데이터 등 어레이 데이터를 csv 파일로 저장하기

### 단일 센서 데이터

In [2]:
x1 = np.random.rand(10)
x1

array([0.85686475, 0.79257441, 0.34144048, 0.69826229, 0.77756884,
       0.07300321, 0.03403364, 0.68851644, 0.03133929, 0.64165934])

In [3]:
np.savetxt("test_1.csv", x1, delimiter=",")

### 파일 내용 출력
- read()와 print() 함수 사용
- !cat, !type 등 명령어를 사용하지 않아도 됨

In [4]:
with open('test_1.csv') as f: 
    print(f.read())

8.568647526103455592e-01
7.925744082462490292e-01
3.414404823884820139e-01
6.982622887177671878e-01
7.775688368700645059e-01
7.300320722569886289e-02
3.403364255278462647e-02
6.885164367691641862e-01
3.133928523699547330e-02
6.416593393854217453e-01



In [5]:
# 데이터프레임으로 읽기
df1 = pd.read_csv('test_1.csv', header=None)  
df1

0
0  0.856865
1  0.792574
2  0.341440
3  0.698262
4  0.777569
5  0.073003
6  0.034034
7  0.688516
8  0.031339
9  0.641659

### 5개의 센서 데이터

In [6]:
# (10,5) 구조의 데이터
x2 = np.arange(50).reshape(10,5)
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [7]:
np.savetxt("test_2.csv", x2, delimiter=",")

In [8]:
df = pd.read_csv('test_2.csv', header=None)  
df
# 디폴트로 첫 행을 컬럼명으로 인식한다, 컬럼명 행이 없다는 것을 명시해야 한다

0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4  20.0  21.0  22.0  23.0  24.0
5  25.0  26.0  27.0  28.0  29.0
6  30.0  31.0  32.0  33.0  34.0
7  35.0  36.0  37.0  38.0  39.0
8  40.0  41.0  42.0  43.0  44.0
9  45.0  46.0  47.0  48.0  49.0

In [9]:
# 어레이로 변환하기
df.values

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]])

### read_csv 옵션
 - nrows=10 (상위 10줄만 읽기)
 - skiprows = 10 (10줄 건너뛰기)
 - skiprows = (1,2,5) (1, 2, 5행 건너뛰기)
 - skipfooter = 1000 (맨 뒤의 1000줄 읽지 않기)
 - usecols= (0,2,4) (해당 컬럼만 읽는다)

In [10]:
# 일부 행만 읽기 nrows 사용 (3줄 읽기)
df2 = pd.read_csv('test_2.csv', nrows=3, header=None)
df2

0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0

In [11]:
df2 = pd.read_csv('test_2.csv', skiprows=3, header=None)
df2

0     1     2     3     4
0  15.0  16.0  17.0  18.0  19.0
1  20.0  21.0  22.0  23.0  24.0
2  25.0  26.0  27.0  28.0  29.0
3  30.0  31.0  32.0  33.0  34.0
4  35.0  36.0  37.0  38.0  39.0
5  40.0  41.0  42.0  43.0  44.0
6  45.0  46.0  47.0  48.0  49.0

In [12]:
df2 = pd.read_csv('test_2.csv', skiprows=(1,3), header=None)
df2

0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1  10.0  11.0  12.0  13.0  14.0
2  20.0  21.0  22.0  23.0  24.0
3  25.0  26.0  27.0  28.0  29.0
4  30.0  31.0  32.0  33.0  34.0
5  35.0  36.0  37.0  38.0  39.0
6  40.0  41.0  42.0  43.0  44.0
7  45.0  46.0  47.0  48.0  49.0

In [13]:
df2 = pd.read_csv('test_2.csv', skipfooter=6, header=None)
df2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

## 어레이로 바로 읽기
- 데이터 크기가 크면 데이터프레임을 만드는데 시간이 많이 걸린다
- loadtxt() 사용

In [14]:
array_data = np.loadtxt('test_2.csv', delimiter=',')
array_data

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]])

In [15]:
# 일부 라인만 읽기 (데이터가 너무 클 때)
np.loadtxt('test_2.csv', delimiter=',', max_rows=5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [16]:
# 일부 컬럼만 읽을 때
np.loadtxt('test_2.csv', delimiter=',', usecols=(0,2,4))

array([[ 0.,  2.,  4.],
       [ 5.,  7.,  9.],
       [10., 12., 14.],
       [15., 17., 19.],
       [20., 22., 24.],
       [25., 27., 29.],
       [30., 32., 34.],
       [35., 37., 39.],
       [40., 42., 44.],
       [45., 47., 49.]])

## csv 파일로 출력
- 판다스의 to_csv() 사용

In [17]:
df = pd.read_csv('test_2.csv', header=None)  
df

0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4  20.0  21.0  22.0  23.0  24.0
5  25.0  26.0  27.0  28.0  29.0
6  30.0  31.0  32.0  33.0  34.0
7  35.0  36.0  37.0  38.0  39.0
8  40.0  41.0  42.0  43.0  44.0
9  45.0  46.0  47.0  48.0  49.0

In [29]:
df.to_csv('output.csv')
with open('output.csv') as f: print(f.read())

,0,1,2,3,4
0,0.0,1.0,2.0,3.0,4.0
1,5.0,6.0,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0
4,20.0,21.0,22.0,23.0,24.0
5,25.0,26.0,27.0,28.0,29.0
6,30.0,31.0,32.0,33.0,34.0
7,35.0,36.0,37.0,38.0,39.0
8,40.0,41.0,42.0,43.0,44.0
9,45.0,46.0,47.0,48.0,49.0



- 데이터 프레임의 인덱스와 컬럼도 포함되어 저장된다
- 인덱스를 제거하려면, index=False 를 지정한다

In [77]:
df.to_csv('output.csv', index=False, header=False)
with open('output.csv') as f: print(f.read())

0.0,1.0,2.0,3.0,4.0
5.0,6.0,7.0,8.0,9.0
10.0,11.0,12.0,13.0,14.0
15.0,16.0,17.0,18.0,19.0
20.0,21.0,22.0,23.0,24.0
25.0,26.0,27.0,28.0,29.0
30.0,31.0,32.0,33.0,34.0
35.0,36.0,37.0,38.0,39.0
40.0,41.0,42.0,43.0,44.0
45.0,46.0,47.0,48.0,49.0



## 액셀 파일로 출력

In [36]:
df.to_excel('output.xlsx', index=False, header=False)
pd.read_excel('output.xlsx', header=None)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

### 액셀 한글 인코딩
- 문자의 인코딩은 기본적으로 utf-8 을 사용한다
- 그러나 한글의 경우 다른 인코딩으로 저장되는 경우가 있다
 - MS 액셀에서 csv로 저장할 때 한글이 cpc949로 인코딩된다. 이때는 아래 옵션이 필요하다
 - encoding = 'cpc949'
 - encoding = 'EUK-KR'을 선택해야 하는 경우도 있다

## zip 파일 
### zip 파일 만들기
- output.csv 을 output.zip로 압축하는 경우

In [76]:
import zipfile
with zipfile.ZipFile('output.zip', 'w') as z:
    z.write('output.csv')

FileNotFoundError: ignored

### zip 파일 풀기

In [38]:
with zipfile.ZipFile("output.zip", 'r') as z: 
    print(z.namelist()) # zip에 포한된 파일목록 보기
    z.extractall() # 압축 풀기, 하위 폴더 지정 가능

['output.csv']


- zip 파일은 read_csv에서 바로 읽을 수 있다 (압축을 풀 필요 없다)

In [39]:
pd.read_csv('output.zip', header=None)  

0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4  20.0  21.0  22.0  23.0  24.0
5  25.0  26.0  27.0  28.0  29.0
6  30.0  31.0  32.0  33.0  34.0
7  35.0  36.0  37.0  38.0  39.0
8  40.0  41.0  42.0  43.0  44.0
9  45.0  46.0  47.0  48.0  49.0

# 폴더 작업

## 현재 폴더 위치 보기

In [40]:
import os
cur_dir = os.getcwd()
cur_dir

'/content'

## 폴더의 파일 목록 얻기
- glob() 사용: 파일 타입을 지정할 수 있다
- listdir() 사용: 경로를 줄 수 있다

### glob()를 사용

In [41]:
# 파일 목록 얻기
from glob import glob
sorted(glob('*.ipynb'))

[]

### listdir()를 사용

In [42]:
# 파일과 폴더 목록 얻기
file_list = os.listdir()
sorted(file_list)

['.config',
 'output.csv',
 'output.xlsx',
 'output.zip',
 'sample_data',
 'test_1.csv',
 'test_2.csv']

In [43]:
# 파일의 전체 경로, full path 만들기
cur_dir = os.getcwd()
for file_name in file_list:
    full_path = os.path.join(cur_dir, file_name)
    print(full_path)

/content/.config
/content/test_1.csv
/content/output.zip
/content/output.csv
/content/output.xlsx
/content/test_2.csv
/content/sample_data


## 폴더 찾기
- 폴더인지를 검사하는 isdir() 함수 사용

In [44]:
for file_name in file_list:
    if os.path.isdir(file_name):
        print("폴더:", file_name)

폴더: .config
폴더: sample_data


## (연습) 랜덤넘버를 생성하는 센서 3개의 출력 100개를 csv, zip 파일로 만들기
- 랜덤넘버를 (100,3) 구조로 만들고 이를 csv 및 zip 파일로 만든다
- 힌트: random.rand(100,3)으로 2차원 랜덤넘버를 생성할 수 있다

In [63]:
# (풀이) rand(100,3)  #jms 연습
t1 = rand(100,3)
t1
type(t1)

my_df = pd.DataFrame(t1)
my_df
my_df.to_csv('output_t1.csv', index=False, header=False)
import zipfile
with zipfile.ZipFile('output_t1.zip', 'w') as z:
    z.write('output_t1.csv')

In [64]:
## 기타 폴더 및 파일 관리 함수
 - os 패키지에서 제공하는 함수
 - 폴더 생성 mkdir()
 - 폴더 위치 이동 chdir()
 - 파일 이름 변경 rename()
 - 파일 삭제 remove()
 - 폴더 삭제 rmdir()

SyntaxError: ignored

In [65]:
# 폴더가 없으면 새로 만들기
if not os.path.exists("./data_tmp"):
    os.mkdir("./data_tmp")

In [67]:
# (참고) 폴더가 있으면 "지우고" 새로 만들기
if os.path.exists("./data_tmp"):
    os.rmdir("./data_tmp")
    os.mkdir("./data_tmp")

In [68]:
# jms 현재 폴더확인
!pwd   # 현재 작업하는 폴더가 어디냐를 보는것

/content


In [69]:
# 폴더 이동
os.chdir('./data_tmp')

In [70]:
os.getcwd()

'/content/data_tmp'

In [72]:
# 폴더 이동
os.chdir('../')

In [73]:
os.getcwd()

'/'

In [74]:
!pwd

/


In [80]:
os.chdir('./content')

In [81]:
!pwd

/content


In [86]:
# 파일 이름 변경
os.rename('new_output.csv','output.csv')
#with open('new_output_t1.csv') as f: print(f.read())

In [ ]:
# 파일 삭제
os.remove('new_output.csv')

In [ ]:
# 폴더 삭제
os.rmdir('./data_tmp')

## (연습) 현재 폴더에서 test로 시작하는 파일명을 모두 t_test로 시작하는 이름으로 변경


In [97]:
!pwd

/content


In [96]:
# (풀이)
from glob import glob
f_list = glob('test*')
f_list

[]

In [ ]:
# (풀이) jms방식
from glob import glob
glob('test*')
f.replace('test*', 't_test*')

## (연습) 현재 폴더에서 t_test로 시작하는 파일명을 모두 test로 시작하는 이름으로 변경


In [ ]:
# (풀이)



# 정답

## (연습) 랜덤넘버를 생성하는 센서 3개의 출력 100개를 csv, zip 파일로 만들기
- 랜덤넘버를 (100,3) 구조로 만들고 이를 csv 및 zip 파일로 만든다
- 힌트: random.rand(100,3)으로 2차원 랜덤넘버를 생성할 수 있다

In [ ]:
x = np.random.rand(100,3)
x[:5]

array([[0.70915461, 0.33128823, 0.76599516],
       [0.36978895, 0.54839227, 0.31758868],
       [0.0735438 , 0.97667148, 0.82913036],
       [0.65087652, 0.57024871, 0.18733589],
       [0.34298556, 0.10352711, 0.78348176]])

In [ ]:
np.savetxt("test_3.csv", x, delimiter=",")
# 저장 확인
df = pd.read_csv('test_3.csv', header=None)  
df

0         1         2
0   0.709155  0.331288  0.765995
1   0.369789  0.548392  0.317589
2   0.073544  0.976671  0.829130
3   0.650877  0.570249  0.187336
4   0.342986  0.103527  0.783482
..       ...       ...       ...
95  0.186380  0.317175  0.584919
96  0.691522  0.605399  0.328059
97  0.516537  0.351971  0.802015
98  0.507388  0.821044  0.696439
99  0.534160  0.109166  0.714470

[100 rows x 3 columns]

In [ ]:
# 압축하기
with zipfile.ZipFile('output_3.zip', 'w') as z:
    z.write('test_3.csv')

In [ ]:
# 확인
df = pd.read_csv('output_3.zip', header=None)  
df

0         1         2
0   0.709155  0.331288  0.765995
1   0.369789  0.548392  0.317589
2   0.073544  0.976671  0.829130
3   0.650877  0.570249  0.187336
4   0.342986  0.103527  0.783482
..       ...       ...       ...
95  0.186380  0.317175  0.584919
96  0.691522  0.605399  0.328059
97  0.516537  0.351971  0.802015
98  0.507388  0.821044  0.696439
99  0.534160  0.109166  0.714470

[100 rows x 3 columns]

## (연습) 현재 폴더에서 test로 시작하는 파일명을 모두 t_test로 시작하는 이름으로 변경


In [98]:
from glob import glob
f_list = glob('test*')
f_list

[]

In [99]:
for file in f_list:
    os.rename(file, 't_'+file)

glob('t_*')

['t_test_1.csv', 't_test_2.csv']

## (연습) 현재 폴더에서 t_test로 시작하는 파일명을 모두 test로 시작하는 이름으로 변경


In [100]:
from glob import glob
f_list = glob('t_test*')
f_list

['t_test_1.csv', 't_test_2.csv']

In [101]:
for file in f_list:
    os.rename(file, file[2:])
glob('test*')

['test_1.csv', 'test_2.csv']